import java.util.HashSet;
import java.util.Set;

public class HashSet101
{

	public static void main(String[] args)
	{
		Set<Integer> nums;
		nums = new HashSet<Integer>();
		nums.add(3);
		nums.add(2);
		System.out.println(nums.add(6));
		System.out.println("nums: " + nums + "\n");
		
		System.out.println(nums.add(6)); //duplicates will not be added
		System.out.println("nums: " + nums + "\n");
		
		nums.add(-4);
		System.out.println("nums: " + nums + "\n"); //order is determined by the hashCode generated by a hashing algorithm
		
		//removing elements
		System.out.println(nums.remove(2));
		System.out.println(nums.remove(5));
		System.out.println("nums: " + nums + "\n");

		System.out.println("==============================================\n");
		
		Set<String> words;
		words = new HashSet<String>();
		words.add("rock");
		words.add("paper");
		System.out.println(words.add("scissors"));
		System.out.println("words: " + words + "\n");
		
		System.out.println(words.add("rock")); //duplicates will not be added
		System.out.println("words: " + words + "\n");
		
		words.add("lizard");
		System.out.println("words: " + words + "\n"); //order is determined by the hashCode generated by a hashing algorithm

		//removing elements
		System.out.println(words.remove("scissors"));
		System.out.println(words.remove("spock"));
		System.out.println("nums: " + words + "\n");
	}

}
